### PR TITLE
chore: update Uptrace version

### PR DESCRIPTION
**Pull request by vmihailenco**
The new version should perform better in this particular benchmark.

Also, enabled LZ4 compression in the official Go client example for more fairness.

### CODE REVIEW

**Comment by ernado** [comment]
> Also, enabled LZ4 compression in the official Go client example for more fairness.

Should be disabled in all clients

**Comment by ernado** [comment]
```console
$ hyperfine ch-bench-faster ch-bench-uptrace
Benchmark 1: ch-bench-faster
  Time (mean ± σ):     628.7 ms ± 129.6 ms    [User: 112.8 ms, System: 354.4 ms]
  Range (min … max):   429.6 ms … 841.2 ms    10 runs
 
Benchmark 2: ch-bench-uptrace
  Time (mean ± σ):     22.964 s ±  0.259 s    [User: 21.803 s, System: 1.381 s]
  Range (min … max):   22.557 s … 23.313 s    10 runs
 
Summary
  'ch-bench-faster' ran
   36.52 ± 7.54 times faster than 'ch-bench-uptrace'
```
```console
$ /usr/bin/time -v ch-bench-uptrace
22.681s 500000000
        Command being timed: "ch-bench-uptrace"
        User time (seconds): 21.73
        System time (seconds): 1.32
        Percent of CPU this job got: 101%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:22.79
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 6933544
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1749331
        Voluntary context switches: 11701
        Involuntary context switches: 125
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```
5G to 6GB RSS, 20x to 36x ratio (probably due to LZ4 which should be disabled by default)

**Comment by vmihailenco** [comment]
I've removed the change regarding compression in the official CH client.

>5G to 6GB RSS, 20x to 36x ratio (probably due to LZ4 which should be disabled by default)

It looks like you did not recompile the uptrace binary. Locally I see

```
ch-bench-official git:(fix/update-uptrace) go run .
7.402s 500000000

ch-bench-uptrace git:(fix/update-uptrace) go run .
6.671s 500000000
```

**Comment by ernado** [comment]
Yes, now it is much faster, great job :zap:

**Pull request merged**
